app:
  build: "."
  command: "nodemon ./node_modules/.bin/rapptor"
  environment:
    PORT: 8080
    SLACK_HOOK: '${SLACK_HOOK}'
  ports:
    - "8080:8080"
  volumes:
    - ".:/app"
    - "/app/node_modules"
